export const REGISTER_START: 'REGISTER_START' = 'REGISTER_START';
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';

export const LOGIN_START: 'LOGIN_START' = 'LOGIN_START';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';

export const GET_PROFILE_START: 'GET_PROFILE_START' = 'GET_PROFILE_START';
export const GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS' = 'GET_PROFILE_SUCCESS';

export const UPDATE_PROFILE_START: 'UPDATE_PROFILE_START' = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS' = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED: 'UPDATE_PROFILE_FAILED' = 'UPDATE_PROFILE_FAILED';

export const LOGOUT_START: 'LOGOUT_START' = 'LOGOUT_START';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';

export const RESET_PASSWORD_START: 'RESET_PASSWORD_START' = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED';

export const SAVE_RESET_PASSWORD_START: 'SAVE_RESET_PASSWORD_START' = 'SAVE_RESET_PASSWORD_START';
export const SAVE_RESET_PASSWORD_SUCCESS: 'SAVE_RESET_PASSWORD_SUCCESS' = 'SAVE_RESET_PASSWORD_SUCCESS';
export const SAVE_RESET_PASSWORD_FAILED: 'SAVE_RESET_PASSWORD_FAILED' = 'SAVE_RESET_PASSWORD_FAILED';

export const CLEAR_USER_DATA: 'CLEAR_USER_DATA' = 'CLEAR_USER_DATA';

export const CLEAR_SUCCESS_FLAG: 'CLEAR_SUCCESS_FLAG' = 'CLEAR_SUCCESS_FLAG';

export const CLEAR_MESSAGE: 'CLEAR_MESSAGE' = 'CLEAR_MESSAGE';

export const CHANGE_FORGOT_FORM: 'CHANGE_FORGOT_FORM' = 'CHANGE_FORGOT_FORM';