export const START_REQUEST: 'START_REQUEST' = 'START_REQUEST';
export const FINISH_REQUEST: 'FINISH_REQUEST' = 'FINISH_REQUEST';

export const PUT_ORDER_IDS_INGREDIENTS: 'PUT_ORDER_IDS_INGREDIENTS' = 'PUT_ORDER_IDS_INGREDIENTS';

export const CLEAR_ORDER: 'CLEAR_ORDER' = 'CLEAR_ORDER';