export const START_LOADING: 'START_LOADING' = 'START_LOADING';
export const END_LOADING: 'END_LOADING' = 'END_LOADING';

export const ADD_CURRENT_INGREDIENT: 'ADD_CURRENT_INGREDIENT' = 'ADD_CURRENT_INGREDIENT';
export const DELETE_CURRENT_INGREDIENT: 'DELETE_CURRENT_INGREDIENT' = 'DELETE_CURRENT_INGREDIENT';

export const ADD_INGREDIENT_IN_CONSTRUCTOR: 'ADD_INGREDIENT_IN_CONSTRUCTOR' = 'ADD_INGREDIENT_IN_CONSTRUCTOR';
export const DELETE_INGREDIENT_IN_CONSTRUCTOR: 'DELETE_INGREDIENT_IN_CONSTRUCTOR' = 'DELETE_INGREDIENT_IN_CONSTRUCTOR';

export const INCREMENT_COUNT: 'INCREMENT_COUNT' = 'INCREMENT_COUNT';

export const UPDATE_MOVE_CARDS: 'UPDATE_MOVE_CARDS' = 'UPDATE_MOVE_CARDS';

export const CLEAR_CONSTRUCTOR: 'CLEAR_CONSTRUCTOR' = 'CLEAR_CONSTRUCTOR';